steps:
  - name: 'gcr.io/cloud-builders/apt'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Installing dependencies..."
        apt-get update -y
        apt-get install -y mysql-client openjdk-17-jdk maven

  - name: 'gcr.io/cloud-builders/mysql'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Checking MySQL connection..."
        mysql -h "db-spring-boot.c19mi8lie4w7.us-east-1.rds.amazonaws.com" -P "3306" -u "denys" -p"Server1q23" -e "USE lab5_db" 2>/dev/null
        if [ $? -eq 0 ]; then
          echo "Connected to MySQL successfully."
        else
          echo "Failed to connect to MySQL."
          exit 1
        fi

  - name: 'gcr.io/cloud-builders/maven'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'mvn clean install'

artifacts:
  objects:
    location: 'gs://your-bucket-name/'
    paths:
      - 'target/lab5-app.jar'
      - 'scripts/*.sh'
      - 'appspec.yml'
