steps:
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Installing dependencies..."
        apt-get update -y
        apt-get install -y mysql-client openjdk-17-jdk maven

  - name: 'maven:3.8.4'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'mvn clean install'

artifacts:
  objects:
    location: 'gs://your-bucket-name/'
    paths:
      - 'target/lab5-app.jar'
      - 'scripts/*.sh'
      - 'appspec.yml'
